# Generated by Django 5.0.2 on 2024-02-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps_task_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasksmodels",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
    ]
